# Generated by Django 3.2 on 2021-04-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='../images/'),
        ),
    ]
