# Generated by Django 3.2 on 2021-05-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_word_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ansver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='right_ansver',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
