# Generated by Django 3.2 on 2021-05-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210508_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(default='You have not entered a description for this word', max_length=500),
        ),
    ]
